<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="products.xsl"?>
<!DOCTYPE products [
  <!ELEMENT products (product+)>
  <!ELEMENT product (product_id, product_name, category, unit_price, stock_quantity)>
  <!ELEMENT product_id (#PCDATA)>
  <!ELEMENT product_name (#PCDATA)>
  <!ELEMENT category (#PCDATA)>
  <!ELEMENT unit_price (#PCDATA)>
  <!ELEMENT stock_quantity (#PCDATA)>
]>
<products>
  <product>
    <product_id>P001</product_id>
    <product_name>LOGITECH G PRO-X SUPERLIGHT</product_name>
    <category>อิเล็กทรอนิกส์</category>
    <unit_price>3,990</unit_price>
    <stock_quantity>50</stock_quantity>
  </product>
  <product>
    <product_id>P002</product_id>
    <product_name>GLORIOUS MODEL O WIRELESS</product_name>
    <category>อิเล็กทรอนิกส์</category>
    <unit_price>3,590</unit_price>
    <stock_quantity>50</stock_quantity>
  </product>
  <product>
    <product_id>P003</product_id>
    <product_name>VXE Dragonfly R1 Pro Max</product_name>
    <category>อิเล็กทรอนิกส์</category>
    <unit_price>1,338</unit_price>
    <stock_quantity>50</stock_quantity>
  </product>
  <product>
    <product_id>P004</product_id>
    <product_name>VGN F1 MOBA</product_name>
    <category>อิเล็กทรอนิกส์</category>
    <unit_price>1,594</unit_price>
    <stock_quantity>50</stock_quantity>
  </product>
  <product>
    <product_id>P005</product_id>
    <product_name>Loga Deva 4K</product_name>
    <category>อิเล็กทรอนิกส์</category>
    <unit_price>2,390</unit_price>
    <stock_quantity>50</stock_quantity>
  </product>
</products>
